package:
  name: gma
  version: "1.1.5"

source:
  path: src

requirements:
  build:
    - make
  run:
    - python >=3.10
    - openpyxl
    - reportlab
    - snpeff =5.2
    - snpsift =5.2
    - kraken2
    - bracken
    - bwa
    - samtools
    - bcftools
    - bedtools
    - cutadapt
    - fastqc
    - seqkit
    - tb-profiler =6.6.6

test:
  commands:
    - gmawgs --help
    - snpEff -version 2>&1 | grep "5.2"

about:
  home: https://github.com/IRCGP-Lab/gmawgs
  license: GPL-3.0-or-later
  license_family: GPL
  summary: "GenoMycAnalyzer: WGS Bioinformatics Pipeline for MTB"
  
  doc_url: https://link.springer.com/article/10.1186/s12864-024-10320-3
  
  description: |
    GenoMycAnalyzer (GMA) is a comprehensive WGS Bioinformatics Pipeline for Mycobacterium tuberculosis.
    
    Reference / Citation: 
    Kim et al. (2024). "GenoMycAnalyzer: a web-based tool for species and drug resistance prediction for Mycobacterium genomes"
    BMC Genomics, https://link.springer.com/article/10.1186/s12864-024-10320-3