#!/usr/bin/env python3

import sys
import os

# ----------------------------------------------------------------------
# Lineage database definitions (as provided)
# ----------------------------------------------------------------------

LINEAGE_SEQ = "GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCAGCCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC"

LINEAGE_MARK = [
    {'Idx':0,'Pos':615938,'Ref':'G'},{'Idx':1,'Pos':763886,'Ref':'C'},{'Idx':2,'Pos':4407873,'Ref':'C'},{'Idx':3,'Pos':765171,'Ref':'C'},{'Idx':4,'Pos':4404247,'Ref':'G'},
    {'Idx':5,'Pos':529363,'Ref':'C'},{'Idx':6,'Pos':3021283,'Ref':'G'},{'Idx':7,'Pos':1750465,'Ref':'T'},{'Idx':8,'Pos':3216553,'Ref':'G'},{'Idx':9,'Pos':6124,'Ref':'C'},
    {'Idx':10,'Pos':2622402,'Ref':'G'},{'Idx':11,'Pos':1491275,'Ref':'G'},{'Idx':12,'Pos':4407780,'Ref':'C'},{'Idx':13,'Pos':403481,'Ref':'C'},{'Idx':14,'Pos':285096,'Ref':'G'},
    {'Idx':15,'Pos':2738352,'Ref':'C'},{'Idx':16,'Pos':1136017,'Ref':'A'},{'Idx':17,'Pos':590595,'Ref':'G'},{'Idx':18,'Pos':528781,'Ref':'G'},{'Idx':19,'Pos':2737201,'Ref':'A'},
    {'Idx':20,'Pos':2763624,'Ref':'G'},{'Idx':21,'Pos':1245275,'Ref':'C'},{'Idx':22,'Pos':61842,'Ref':'T'},{'Idx':23,'Pos':282892,'Ref':'C'},{'Idx':24,'Pos':497491,'Ref':'G'},
    {'Idx':25,'Pos':1834177,'Ref':'A'},{'Idx':26,'Pos':4308395,'Ref':'G'},{'Idx':27,'Pos':648465,'Ref':'A'},{'Idx':28,'Pos':1881090,'Ref':'C'},{'Idx':29,'Pos':2505085,'Ref':'G'},
    {'Idx':30,'Pos':4243460,'Ref':'C'},{'Idx':31,'Pos':892416,'Ref':'C'},{'Idx':32,'Pos':797736,'Ref':'C'},{'Idx':33,'Pos':2078246,'Ref':'C'},{'Idx':34,'Pos':1947282,'Ref':'A'},
    {'Idx':35,'Pos':4248115,'Ref':'C'},{'Idx':36,'Pos':1692069,'Ref':'A'},{'Idx':37,'Pos':3836274,'Ref':'G'},{'Idx':38,'Pos':346693,'Ref':'G'},{'Idx':39,'Pos':342873,'Ref':'C'},
    {'Idx':40,'Pos':762434,'Ref':'T'},{'Idx':41,'Pos':3273107,'Ref':'C'},{'Idx':42,'Pos':958362,'Ref':'C'},{'Idx':43,'Pos':1084911,'Ref':'G'},{'Idx':44,'Pos':1591545,'Ref':'G'},
    {'Idx':45,'Pos':3722702,'Ref':'G'},{'Idx':46,'Pos':1237818,'Ref':'C'},{'Idx':47,'Pos':2874344,'Ref':'G'},{'Idx':48,'Pos':4326176,'Ref':'T'},{'Idx':49,'Pos':17842,'Ref':'G'},
    {'Idx':50,'Pos':763031,'Ref':'T'},{'Idx':51,'Pos':931123,'Ref':'T'},{'Idx':52,'Pos':2825466,'Ref':'G'},{'Idx':53,'Pos':4407588,'Ref':'T'},{'Idx':54,'Pos':62657,'Ref':'G'},
    {'Idx':55,'Pos':514245,'Ref':'C'},{'Idx':56,'Pos':1006080,'Ref':'G'},{'Idx':57,'Pos':1850119,'Ref':'C'},{'Idx':58,'Pos':4240897,'Ref':'C'},{'Idx':59,'Pos':541048,'Ref':'T'},
    {'Idx':60,'Pos':1109535,'Ref':'G'},{'Idx':61,'Pos':4229087,'Ref':'C'},{'Idx':62,'Pos':286300,'Ref':'C'},{'Idx':63,'Pos':4269540,'Ref':'G'},{'Idx':64,'Pos':891756,'Ref':'A'},
    {'Idx':65,'Pos':3147742,'Ref':'A'},{'Idx':66,'Pos':760115,'Ref':'C'},{'Idx':67,'Pos':107794,'Ref':'C'},{'Idx':68,'Pos':342340,'Ref':'C'},{'Idx':69,'Pos':2488724,'Ref':'C'},
    {'Idx':70,'Pos':4404313,'Ref':'G'},{'Idx':71,'Pos':1564799,'Ref':'C'},{'Idx':72,'Pos':58786,'Ref':'G'},{'Idx':73,'Pos':1466779,'Ref':'C'},{'Idx':74,'Pos':2411730,'Ref':'G'},
    {'Idx':75,'Pos':783601,'Ref':'A'},{'Idx':76,'Pos':870187,'Ref':'C'},{'Idx':77,'Pos':353766,'Ref':'T'},{'Idx':78,'Pos':1487796,'Ref':'C'},{'Idx':79,'Pos':1455780,'Ref':'T'},
    {'Idx':80,'Pos':611463,'Ref':'G'},{'Idx':81,'Pos':1880850,'Ref':'G'},{'Idx':82,'Pos':2156847,'Ref':'G'},{'Idx':83,'Pos':764995,'Ref':'C'},{'Idx':84,'Pos':1452071,'Ref':'C'},
    {'Idx':85,'Pos':3073868,'Ref':'T'},{'Idx':86,'Pos':615614,'Ref':'C'},{'Idx':87,'Pos':825585,'Ref':'T'},{'Idx':88,'Pos':1647807,'Ref':'T'},{'Idx':89,'Pos':3414791,'Ref':'G'},
    {'Idx':90,'Pos':4316114,'Ref':'G'},{'Idx':91,'Pos':784581,'Ref':'G'},{'Idx':92,'Pos':3388166,'Ref':'C'},{'Idx':93,'Pos':403364,'Ref':'G'},{'Idx':94,'Pos':2077253,'Ref':'G'},
    {'Idx':95,'Pos':2518919,'Ref':'G'},{'Idx':96,'Pos':1297327,'Ref':'G'},{'Idx':97,'Pos':3977226,'Ref':'G'},{'Idx':98,'Pos':1274335,'Ref':'G'},{'Idx':99,'Pos':4398141,'Ref':'G'},
    {'Idx':100,'Pos':784440,'Ref':'G'},{'Idx':101,'Pos':1132368,'Ref':'C'},{'Idx':102,'Pos':225495,'Ref':'T'},{'Idx':103,'Pos':1502120,'Ref':'C'},{'Idx':104,'Pos':4307886,'Ref':'G'},
    {'Idx':105,'Pos':2905505,'Ref':'G'},{'Idx':106,'Pos':4151558,'Ref':'G'},{'Idx':107,'Pos':355181,'Ref':'G'},{'Idx':108,'Pos':15036,'Ref':'C'},{'Idx':109,'Pos':342201,'Ref':'C'},
    {'Idx':110,'Pos':2694560,'Ref':'G'},{'Idx':111,'Pos':4249012,'Ref':'G'},{'Idx':112,'Pos':985287,'Ref':'G'},{'Idx':113,'Pos':4246508,'Ref':'G'},{'Idx':114,'Pos':7892,'Ref':'G'},
    {'Idx':115,'Pos':620029,'Ref':'C'},{'Idx':116,'Pos':1719757,'Ref':'G'},{'Idx':117,'Pos':18091,'Ref':'G'},{'Idx':118,'Pos':3466426,'Ref':'G'},{'Idx':119,'Pos':4260268,'Ref':'G'},
    {'Idx':120,'Pos':874787,'Ref':'G'},{'Idx':121,'Pos':4406749,'Ref':'G'},{'Idx':122,'Pos':1098698,'Ref':'C'},{'Idx':123,'Pos':1501468,'Ref':'G'},{'Idx':124,'Pos':4125058,'Ref':'G'},
    {'Idx':125,'Pos':4260742,'Ref':'G'},{'Idx':126,'Pos':896119,'Ref':'C'},{'Idx':127,'Pos':3570528,'Ref':'C'},{'Idx':128,'Pos':4242883,'Ref':'C'},{'Idx':129,'Pos':2875883,'Ref':'C'},
    {'Idx':130,'Pos':4326739,'Ref':'G'},{'Idx':131,'Pos':4328004,'Ref':'G'},{'Idx':132,'Pos':734562,'Ref':'G'},{'Idx':133,'Pos':4236903,'Ref':'G'},{'Idx':134,'Pos':17665,'Ref':'G'},
    {'Idx':135,'Pos':716918,'Ref':'G'},{'Idx':136,'Pos':4249732,'Ref':'C'},{'Idx':137,'Pos':1130526,'Ref':'G'},{'Idx':138,'Pos':3836739,'Ref':'G'},{'Idx':139,'Pos':2914906,'Ref':'G'},
    {'Idx':140,'Pos':2417281,'Ref':'G'},{'Idx':141,'Pos':8135,'Ref':'C'},{'Idx':142,'Pos':616408,'Ref':'C'},{'Idx':143,'Pos':420008,'Ref':'A'},{'Idx':144,'Pos':1759252,'Ref':'G'},
    {'Idx':145,'Pos':4242643,'Ref':'C'},{'Idx':146,'Pos':8978,'Ref':'C'},{'Idx':147,'Pos':119600,'Ref':'C'},{'Idx':148,'Pos':9566,'Ref':'C'},{'Idx':149,'Pos':1799921,'Ref':'C'},
    {'Idx':150,'Pos':801959,'Ref':'C'},{'Idx':151,'Pos':2859147,'Ref':'C'},{'Idx':152,'Pos':4326928,'Ref':'G'},{'Idx':153,'Pos':982363,'Ref':'G'},{'Idx':154,'Pos':1816587,'Ref':'C'},
    {'Idx':155,'Pos':8876,'Ref':'C'},{'Idx':156,'Pos':1137518,'Ref':'G'},{'Idx':157,'Pos':1834916,'Ref':'A'},{'Idx':158,'Pos':1918281,'Ref':'A'},{'Idx':159,'Pos':3878040,'Ref':'A'},
    {'Idx':160,'Pos':4240153,'Ref':'G'},{'Idx':161,'Pos':4248073,'Ref':'C'},{'Idx':162,'Pos':4267649,'Ref':'A'},{'Idx':163,'Pos':784143,'Ref':'A'},{'Idx':164,'Pos':1799774,'Ref':'C'},
    {'Idx':165,'Pos':3473482,'Ref':'C'},{'Idx':166,'Pos':3837064,'Ref':'G'},{'Idx':167,'Pos':4308411,'Ref':'T'},{'Idx':168,'Pos':221190,'Ref':'G'},{'Idx':169,'Pos':2750052,'Ref':'G'},
    {'Idx':170,'Pos':4229470,'Ref':'T'},{'Idx':171,'Pos':2831482,'Ref':'A'},{'Idx':172,'Pos':62768,'Ref':'A'},{'Idx':173,'Pos':4242970,'Ref':'C'},{'Idx':174,'Pos':1834859,'Ref':'G'},
    {'Idx':175,'Pos':904090,'Ref':'T'},{'Idx':176,'Pos':44812,'Ref':'G'},{'Idx':177,'Pos':4039853,'Ref':'C'}
]

LINEAGE_DB = [
    {'ID':'1','Seq':'AAACGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1','Seq':'AAATACGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.1','Seq':'AAATATATGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.1.1','Seq':'AAATATACACGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.2','Seq':'AAATACGTGTAGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.3','Seq':'AAATACGTGCGATCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.3.1','Seq':'AAATACGTGCGATTGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.3.2','Seq':'AAATACGTGCGATCTCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.1.3.3','Seq':'AAATACGTGCGATCGTAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.2','Seq':'AAACGCGTGCGGCCGCGGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.2.1','Seq':'AAACGCGTGCGGCCGCGAGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.2.2','Seq':'AAACGCGTGCGGCCGCGGAAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.2.2.1','Seq':'AAACGCGTGCGGCCGCGGACGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.3','Seq':'AAACGCGTGCGGCCGCAGGAACTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.3.1','Seq':'AAACGCGTGCGGCCGCAGGAATTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'1.3.2','Seq':'AAACGCGTGCGGCCGCAGGAACCCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAGTGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAACATTCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAACATTTGACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2.2.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAACATTTGGTAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2.2.1.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAACATTTGACGNGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'2.2.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTTACAACATTCCACAGTCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGACGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGAGGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGAGATGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3.1.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGAGGGCCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3.1.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGAGGGCGGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3.1.2.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGAGGGCCAGGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'3.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGTGACGGGCGTCCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTACGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTATGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTATATGTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.1.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTATGCCGACCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.1.3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTATGCCTGTCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.1.3.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTATGCCTGTANAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTACGCCTGCCGGGCCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTACGCCTGCCGGGTTTCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.2.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTACGCCTGCCGGGTTTGACGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTACGCCTGCCGAACCCCGTGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.1.4','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTACGCCTGCCGAACCCCGCCCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGTCACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGTCCCTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.2.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGTCCTTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.2.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGTCACCATGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.2.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGTCACCACGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.2.2.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGTCACCATAAACCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACACTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACACCGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTCAGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTCACGGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTGGGCAAAGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.4','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTGGGCGGGAAGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.4.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTGGGCGGGAAAAGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.4.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTGGGCGGGAAGGTTTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.3.4.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGGACCTTGGGCGGGAAGGTTCAGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.4','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCAGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.4.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCAAAGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.4.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCAAAACCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.4.1.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCAAAAGCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.4.1.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCAAAGCGCAGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.4.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCAGGGCCGGAAGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.5','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGATTGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAACGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.1.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAACAACGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.1.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAACGGGCGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGCACCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.2.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGCATGTCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.2.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGCACCCTCAGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGGGCCCCGGAGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.4','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGGGCCCCGGGAGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.6.5','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGAAGGGCGCGCCCCGGGGAGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.7','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGAGGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.8','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCAAGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.8.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCAACGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.8.2','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCAAGATCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.9.1','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCAGCTGCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.8.3','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCAAGGCGGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'4.9','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGTTGTGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCAGCCCCCCCGGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'5','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCTATTNGCCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'6','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGTGCGAAAGCAACCGTGGTAACGTGC'},
    {'ID':'7','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCTACCGATGCTTAGGGTAACGTGC'},
    {'ID':'8','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTTGTAACGTGC'},
    {'ID':'Bovis','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGCGGTATGC'},
    {'ID':'Caprae','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGCGC'},
    {'ID':'Orygis','Seq':'GCCCGCGTGCGGCCGCAGGAGCTCGAGACGCCCCACAGGCTCCGGGCGTGCCACGCGCCTGCCGAACCCCGCGCGACTCTGGGCCTCTTGGGCGGGGGGGGCTCGGGGCCGGGGGCGGGGGGCGGGCCCCGGGGGGCGGGGCCGTTCCCCCCGGCCGAAAGCAACCGTGGTAACGTTT'}
]

# ----------------------------------------------------------------------
# Helper functions
# ----------------------------------------------------------------------

def parse_vcf(vcf_path):
    """Parse VCF and return dict: pos -> (ref, alt)."""
    variants = {}
    with open(vcf_path, "r") as f:
        for line in f:
            if line.startswith("#"):
                continue
            cols = line.rstrip("\n").split("\t")
            if len(cols) < 5:
                continue
            try:
                pos = int(cols[1])
            except ValueError:
                continue
            ref = cols[3].upper()
            alt_field = cols[4].upper()
            alt = alt_field.split(",")[0]
            variants[pos] = (ref, alt)
    return variants


def build_sample_seq(variants):
    """Return lineage motif sequence for this sample."""
    seq_list = list(LINEAGE_SEQ)
    pos_to_idx = {m["Pos"]: m["Idx"] for m in LINEAGE_MARK}
    pos_to_ref = {m["Pos"]: m["Ref"] for m in LINEAGE_MARK}

    for pos, (ref, alt) in variants.items():
        if pos not in pos_to_idx:
            continue
        idx = pos_to_idx[pos]
        ref_expected = pos_to_ref[pos]
        alt_base = alt[0] if len(alt) > 0 else "N"

        if len(ref) == 1 and len(alt_base) == 1 and ref == ref_expected and alt_base in "ACGTN":
            seq_list[idx] = alt_base

    return "".join(seq_list)


def score_lineages(sample_seq):
    """Compare sample_seq with each LINEAGE_DB entry and return best and second best."""
    best = None
    second = None

    for entry in LINEAGE_DB:
        db_id = entry["ID"]
        db_seq = entry["Seq"]

        matches = 0
        total = 0

        for a, b in zip(sample_seq, db_seq):
            if a == "N" or b == "N":
                continue
            total += 1
            if a == b:
                matches += 1

        score = 100.0 * matches / total if total > 0 else 0.0

        rec = {"ID": db_id, "score": score, "matches": matches, "total": total}

        if best is None or score > best["score"]:
            second = best
            best = rec
        elif second is None or score > second["score"]:
            second = rec

    return best, second


# ----------------------------------------------------------------------
# NEW: lineage formatter
# ----------------------------------------------------------------------

def format_lineage(lineage_id: str):
    """Return (Main_lineage, Sub_lineage) with naming rules applied."""
    if lineage_id is None:
        return "Unknown", "-"

    lineage_id = lineage_id.strip()

    if lineage_id == "" or lineage_id.lower() == "unknown":
        return "Unknown", "-"

    is_numeric_like = all(ch.isdigit() or ch == '.' for ch in lineage_id)

    if is_numeric_like:
        if "." in lineage_id:
            parts = lineage_id.split(".")
            root = parts[0]
            main = f"lineage{root}"
            sub = f"lineage{lineage_id}"
        else:
            main = f"lineage{lineage_id}"
            sub = "-"
        return main, sub

    return f"lineage_{lineage_id}", "-"


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def main():
    if len(sys.argv) != 3:
        sys.stderr.write(
            "Usage: python lineage_call.py <input.vcf> <output_lineage.txt>\n"
        )
        sys.exit(1)

    vcf_path = sys.argv[1]
    out_path = sys.argv[2]

    sample_name = os.path.basename(vcf_path)
    for ext in [".vcf", ".vcf.gz"]:
        if sample_name.endswith(ext):
            sample_name = sample_name[:-len(ext)]
            break

    variants = parse_vcf(vcf_path)
    sample_seq = build_sample_seq(variants)
    best, second = score_lineages(sample_seq)

    with open(out_path, "w") as out:
        out.write(
            "Sample\tLineage_call\tScore\tSecond_best\tSecond_score\tMarkers_used\tMain_lineage\tSub_Lineage\n"
        )

        if best is None:
            main_lin, sub_lin = "Unknown", "-"
            out.write(
                f"{sample_name}\tNA\t0.00\tNA\t0.00\t0\t{main_lin}\t{sub_lin}\n"
            )
            return

        best_id = best["ID"]
        second_id = second["ID"] if second else "NA"
        second_score = second["score"] if second else 0.0

        main_lin, sub_lin = format_lineage(best_id)

        out.write(
            "{}\t{}\t{:.2f}\t{}\t{:.2f}\t{}\t{}\t{}\n".format(
                sample_name,
                best_id,
                best["score"],
                second_id,
                second_score,
                best["total"],
                main_lin,
                sub_lin,
            )
        )


if __name__ == "__main__":
    main()